### PR TITLE
Added patch support

### PR DESCRIPTION
**Pull request by fank**
by adding:
```
-v `pwd`/overwrite:/opt/server-overwrite
```
it will add/overwrite files after updating to support installing mods

### CODE REVIEW

**Comment by psykzz** [comment]
LGTM

**Comment by psykzz** [comment]
Could you do another or updating then read me with usage for this feature ?

**Comment by fank** [comment]
im not good in documentation ... would be good if you could do it.

**Comment by fank** [comment]
It would be nice if you could add me as collaborator.
I know same rule as always, create branches for review, don't push in master .... :D

**Comment by psykzz** [comment]
Bit late, but i added you.
I see your message before.

**Pull request merged**
